var hierarchy =
[
    [ "Seguridad.AES", "class_seguridad_1_1_a_e_s.html", null ],
    [ "Entidad.Registros.Categoria", "class_entidad_1_1_registros_1_1_categoria.html", null ],
    [ "Entidad.Roles.Cliente", "class_entidad_1_1_roles_1_1_cliente.html", null ],
    [ "Entidad.Registros.Compra", "class_entidad_1_1_registros_1_1_compra.html", null ],
    [ "Datos.Conexion", "class_datos_1_1_conexion.html", null ],
    [ "Datos.ConexionMaestra", "class_datos_1_1_conexion_maestra.html", null ],
    [ "Datos.Datos.Registros.DatosCategoria", "class_datos_1_1_datos_1_1_registros_1_1_datos_categoria.html", null ],
    [ "Datos.Datos.Roles.DatosCliente", "class_datos_1_1_datos_1_1_roles_1_1_datos_cliente.html", null ],
    [ "Datos.Datos.Registros.DatosCompra", "class_datos_1_1_datos_1_1_registros_1_1_datos_compra.html", null ],
    [ "Datos.Datos.Registros.DatosPermisos", "class_datos_1_1_datos_1_1_registros_1_1_datos_permisos.html", null ],
    [ "Datos.Datos.Registros.DatosProducto", "class_datos_1_1_datos_1_1_registros_1_1_datos_producto.html", null ],
    [ "Datos.Datos.Roles.DatosProveedor", "class_datos_1_1_datos_1_1_roles_1_1_datos_proveedor.html", null ],
    [ "Datos.Datos.Registros.DatosRol", "class_datos_1_1_datos_1_1_registros_1_1_datos_rol.html", null ],
    [ "Datos.Datos.Roles.DatosUsuario", "class_datos_1_1_datos_1_1_roles_1_1_datos_usuario.html", null ],
    [ "Datos.Datos.Registros.DatosVenta", "class_datos_1_1_datos_1_1_registros_1_1_datos_venta.html", null ],
    [ "Seguridad.Desencryptacion", "class_seguridad_1_1_desencryptacion.html", null ],
    [ "Entidad.Registros.DetalleCompra", "class_entidad_1_1_registros_1_1_detalle_compra.html", null ],
    [ "Entidad.Registros.DetalleVenta", "class_entidad_1_1_registros_1_1_detalle_venta.html", null ],
    [ "Form", null, [
      [ "Datos.ConexionManual", "class_datos_1_1_conexion_manual.html", null ],
      [ "Presentacion.Paneles.PanelAcercaDe", "class_presentacion_1_1_paneles_1_1_panel_acerca_de.html", null ],
      [ "Presentacion.Paneles.PanelCategoria", "class_presentacion_1_1_paneles_1_1_panel_categoria.html", null ],
      [ "Presentacion.Paneles.PanelCliente", "class_presentacion_1_1_paneles_1_1_panel_cliente.html", null ],
      [ "Presentacion.Paneles.PanelCompra", "class_presentacion_1_1_paneles_1_1_panel_compra.html", null ],
      [ "Presentacion.Paneles.PanelConfiguracion", "class_presentacion_1_1_paneles_1_1_panel_configuracion.html", null ],
      [ "Presentacion.Paneles.PanelMantenimiento", "class_presentacion_1_1_paneles_1_1_panel_mantenimiento.html", null ],
      [ "Presentacion.Paneles.PanelProducto", "class_presentacion_1_1_paneles_1_1_panel_producto.html", null ],
      [ "Presentacion.Paneles.PanelProveedor", "class_presentacion_1_1_paneles_1_1_panel_proveedor.html", null ],
      [ "Presentacion.Paneles.PanelRegistros", "class_presentacion_1_1_paneles_1_1_panel_registros.html", null ],
      [ "Presentacion.Paneles.PanelReporte", "class_presentacion_1_1_paneles_1_1_panel_reporte.html", null ],
      [ "Presentacion.Paneles.PanelUsuario", "class_presentacion_1_1_paneles_1_1_panel_usuario.html", null ],
      [ "Presentacion.Paneles.PanelVenta", "class_presentacion_1_1_paneles_1_1_panel_venta.html", null ],
      [ "Presentacion.Recursos.VentCliente", "class_presentacion_1_1_recursos_1_1_vent_cliente.html", null ],
      [ "Presentacion.Recursos.VentCompras", "class_presentacion_1_1_recursos_1_1_vent_compras.html", null ],
      [ "Presentacion.Recursos.VentProducto", "class_presentacion_1_1_recursos_1_1_vent_producto.html", null ],
      [ "Presentacion.Recursos.VentProveedor", "class_presentacion_1_1_recursos_1_1_vent_proveedor.html", null ],
      [ "Presentacion.Recursos.VentRegistros", "class_presentacion_1_1_recursos_1_1_vent_registros.html", null ],
      [ "Presentacion.Recursos.VentVentas", "class_presentacion_1_1_recursos_1_1_vent_ventas.html", null ],
      [ "Presentacion.Ventanas.Carga", "class_presentacion_1_1_ventanas_1_1_carga.html", null ],
      [ "Presentacion.Ventanas.Dashboard", "class_presentacion_1_1_ventanas_1_1_dashboard.html", null ],
      [ "Presentacion.Ventanas.Inicio", "class_presentacion_1_1_ventanas_1_1_inicio.html", null ],
      [ "Presentacion.Ventanas.Login", "class_presentacion_1_1_ventanas_1_1_login.html", null ]
    ] ],
    [ "Logica.Logica.Registros.LogicaCategoria", "class_logica_1_1_logica_1_1_registros_1_1_logica_categoria.html", null ],
    [ "Logica.Logica.Roles.LogicaCliente", "class_logica_1_1_logica_1_1_roles_1_1_logica_cliente.html", null ],
    [ "Logica.Logica.Registros.LogicaCompra", "class_logica_1_1_logica_1_1_registros_1_1_logica_compra.html", null ],
    [ "Logica.Logica.Registros.LogicaPermiso", "class_logica_1_1_logica_1_1_registros_1_1_logica_permiso.html", null ],
    [ "Logica.Logica.Registros.LogicaProducto", "class_logica_1_1_logica_1_1_registros_1_1_logica_producto.html", null ],
    [ "Logica.Logica.Roles.LogicaProveedor", "class_logica_1_1_logica_1_1_roles_1_1_logica_proveedor.html", null ],
    [ "Logica.Logica.Roles.LogicaRol", "class_logica_1_1_logica_1_1_roles_1_1_logica_rol.html", null ],
    [ "Logica.Logica.Roles.LogicaUsuario", "class_logica_1_1_logica_1_1_roles_1_1_logica_usuario.html", null ],
    [ "Logica.Logica.Registros.LogicaVenta", "class_logica_1_1_logica_1_1_registros_1_1_logica_venta.html", null ],
    [ "Presentacion.Recursos.OpcionCombo", "class_presentacion_1_1_recursos_1_1_opcion_combo.html", null ],
    [ "Entidad.Roles.Permiso", "class_entidad_1_1_roles_1_1_permiso.html", null ],
    [ "Entidad.Registros.Producto", "class_entidad_1_1_registros_1_1_producto.html", null ],
    [ "Entidad.Roles.Proveedor", "class_entidad_1_1_roles_1_1_proveedor.html", null ],
    [ "Entidad.Roles.Rol", "class_entidad_1_1_roles_1_1_rol.html", null ],
    [ "UserControl", null, [
      [ "Presentacion.Recursos.RJComboBox", "class_presentacion_1_1_recursos_1_1_r_j_combo_box.html", null ]
    ] ],
    [ "Entidad.Roles.Usuario", "class_entidad_1_1_roles_1_1_usuario.html", null ],
    [ "Entidad.Registros.Venta", "class_entidad_1_1_registros_1_1_venta.html", null ]
];